# Generated by Django 4.2.16 on 2024-09-16 15:11

import courses.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_file_module_alter_image_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='order',
            field=courses.models.OrderField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=courses.models.OrderField(blank=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='order',
            field=courses.models.OrderField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='order',
            field=courses.models.OrderField(blank=True),
        ),
    ]
