# Generated by Django 4.2.16 on 2024-09-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_file_order_alter_image_order_alter_text_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='order',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='order',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='order',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
