# Generated by Django 4.2.16 on 2024-09-19 13:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='star',
            unique_together={('object_id', 'content_type', 'user')},
        ),
    ]
